name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle*','**/settings.gradle') }}
          restore-keys: |
            gradle-wrapper-

      - name: Install Android SDK packages
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          mkdir -p "$HOME/android-sdk"
          export ANDROID_SDK_ROOT="$HOME/android-sdk"
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" >/dev/null || true
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platforms;android-34" >/dev/null || true
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "build-tools;34.0.0" >/dev/null || true
        shell: bash

      - name: Export ANDROID_SDK_ROOT
        run: echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon
